import type { Metadata } from 'next';
import './globals.css';
import Link from 'next/link';
import { FaFacebook , FaInstagram, FaGithub, FaLinkedin } from 'react-icons/fa';
import { ThemeProvider } from '@/components/themeprovider';
import { ModeToggle } from '@/components/themetoggle';

export const metadata: Metadata = {
  title: 'Todo App',
  description: 'Basic Todo App. Generated by 124aris.',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head><meta name="google-adsense-account" content="ca-pub-6557456098546788"/></head>
      <body className="flex flex-col justify-between min-h-screen">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <div>
            <header className='flex justify-end p-8 mr-10'>
              <ModeToggle/>
            </header>
            {children}
          </div>
        </ThemeProvider>
        <footer className="flex justify-center space-x-4 p-6 mt-5">
          <Link href="https://github.com/124aris" target="_blank" rel="noopener noreferrer"><FaGithub className="text-3xl"/></Link>
          <Link href="https://www.linkedin.com/in/muhammad-haris-124aris/" target="_blank" rel="noopener noreferrer"><FaLinkedin className="text-3xl"/></Link>
          <Link href="https://www.facebook.com/profile.php?id=100011322003821" target="_blank" rel="noopener noreferrer"><FaFacebook className="text-3xl"/></Link>
          <Link href="https://www.instagram.com/124aris/" target="_blank" rel="noopener noreferrer"><FaInstagram className="text-3xl"/></Link>
        </footer>
      </body>
    </html>
  );
};
