import type { Metadata } from 'next'
import './globals.css'
import Link from 'next/link'
import {FaFacebook , FaInstagram, FaGithub, FaLinkedin } from 'react-icons/fa';

export const metadata: Metadata = {
  title: 'Todo App',
  description: 'Basic Todo App. Generated by 124aris.',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}
      <footer className="fixed bottom-0 left-0 right-0 flex justify-center space-x-4 p-6">
        <Link href="https://github.com/124aris" target="_blank" rel="noopener noreferrer"><FaGithub className="text-black text-3xl "/></Link>
        <Link href="https://www.linkedin.com/in/muhammad-haris-124aris/" target="_blank" rel="noopener noreferrer"><FaLinkedin className="text-black text-3xl "/></Link>
        <Link href="https://www.facebook.com/profile.php?id=100011322003821" target="_blank" rel="noopener noreferrer"><FaFacebook className="text-black text-3xl "/></Link>
        <Link href="https://www.instagram.com/124aris/" target="_blank" rel="noopener noreferrer"><FaInstagram className="text-black text-3xl "/></Link>
      </footer>
      </body>
    </html>
  )
}
